posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.posts_list,name="home"),
	#url(r'^list/$',views.posts_list,name="home"),
	url(r'^(?P<id>\d+)/details/$',views.posts_detail,name="detail"),
]

ttw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from posts.views import posts_detail,about

urlpatterns = [
	#url(r'^$',"posts.views.posts_list"),
	#url(r'^know_us/$',about,name="know_us"),
    url(r'^admin/', admin.site.urls),
    url(r'^',include("posts.urls",namespace="posts")),
]

posts/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

def upload_location(instance,filename):
	return "%s/%s" %(instance.id,filename)



class Post(models.Model):
	title = models.CharField(max_length=56)
	content = models.TextField()
	tips_type = models.CharField(max_length=100)
	author = models.CharField(max_length=120)
	timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)
	image = models.ImageField(upload_to=upload_location ,
		null=True,blank=True)


	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"id":self.id})

	class Meta:
		ordering = ["-timestamp"]

posts/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post
 

def posts_detail(request,id=None):
	instance = get_object_or_404(Post,id=id)
	return render(request,"posts/detail.html",{"instance":instance})



def about(request):
	return render(request,"posts/about.html",{})



def posts_list(request):
	name_list = Post.objects.all()
	query = request.GET.get("q")
	if query:
		name_list = name_list.filter(
			Q(title__icontains=query) |
			Q(content__icontains=query)
			)
		if not name_list:
			return render(request,"posts/search.html",{'error':"No match Found for your search."})

	paginator = Paginator(name_list,4) # Show 6 contacts per page
	page = request.GET.get('page')
	try:
		name = paginator.page(page)
	except PageNotAnInteger:
# If page is not an integer, deliver first page.
		name = paginator.page(1)
	except EmptyPage:
# If page is out of range (e.g. 9999), deliver last page of results.
		name = paginator.page(paginator.num_pages)

	if query:
		return render(request,"posts/search.html",{'name':name})
	else:
		return render(request,"posts/index.html",{"name":name})

templates/posts/_navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <spa n class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'posts:home' %}" style="margin-left:10px;">Thought of The Day</a>
    </div>



<form class="navbar-form navbar-right" mthod="GET" action="" style="margin-right:20px;">
        <div class="form-group">
          <input type="text" placeholder="Search here" class="form-control" name = "q" value="{{ request.GET.q }}" style="width:350px;height:37px;" />
        </div>
        <button style="height:37px;" type="submit" class="btn btn-primary">Search</button>
      </form>




    <!-- Collect the nav links, forms, and other content for toggling--> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">



      <ul class="nav navbar-nav navbar-right" style="color:white;">
        <li><a href="{% url 'posts:home' %}">Recents</a></li>



<!--

        <form mthod="GET" action="">
<input type="text" placeholder="Search here" name = "q" value="{{ request.GET.q }}" />
<input type="submit" value="Search" />
</form>
-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/posts/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Thought of the day</title>
	<link rel="stylesheet" type="text/css" href='{% static "css/basics_css.css" %}' />
	<link rel="stylesheet" type="text/css" href='{% static "bootstrap/theme.css" %}' />
	<link rel="stylesheet" type="text/css" href='{% static "bootstrap/boot.css" %}' />
	<link rel="stylesheet" type="text/css" href='{% static "bootstrap/bootstrap-theme.min.css" %}' />

	<!-- Place this tag in your head or just before your close body tag. -->
<script src="https://apis.google.com/js/platform.js" async defer></script>


</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



{% include "posts/_navbar.html" %}

{% block cover %}
<div class="banner container-fluid" style="background-image: url({% static 'img/cover.jpg' %});" >
<h1 style="margin-top:150px;font-size:65px;margin-left:50px;">Welcome To Our Blog</h1>
</div>
{% endblock %}

<div class="banner container-fluid" style="height:auto;">
<!-- Google adsense ads here -->


</div>


<div class="container-fluid">

<div class="container left_part">
{% block content %}

{% endblock %}
</div>

<div class="container right-part">
	
<!-- Google adsense vertical ads here -->

</div>
 
<script type="text/javascript" src='{% static "js/bootstrap.min.js" %}'></script>
</body>
</html>

templates/posts/detail.html
{% extends "posts/base.html" %}

{% block cover %}<div class="ban container-fluid">
<!-- adsense ads -->

</div>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-8" style="margin-left:30px;">

    <div class="thumbnail" style="padding-left:35px;">
    {% if instance.image %}
      <img src='{{ instance.image.url }}' class="img-responsive" alt='post{{ i.id }}'>
      {% endif %}
      <div class="caption">
        <h2 style="font-size:45px;"><img src="/static/img/{{ instance.tips_type }}.jpg" style="width:37px;height:37px;">&nbsp;&nbsp;<b>{{instance.title}}</b>    &nbsp;&nbsp;&nbsp;&nbsp;<small style="font-size:17px;">{{ instance.timestamp|timesince }}</small></h2>

        <br><br>

        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

        <!-- Place this tag where you want the share button to render. -->
          <div class="g-plus" data-action="share"></div>

        <p>{{instance.content|linebreaks}}</p>
        <h6>Author - {{ instance.author }}</h6>
          <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5">
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/posts/index.html
{% extends "posts/base.html" %}



{% block content %}
<div class="col-sm-8 col-sm-offset-2">
{% for i in name %}
<div class="row">
  <div class="col-sm-8">
    <div class="thumbnail">
      {% if i.image %}
      <img src='{{ i.image.url }}' class="img-responsive" alt='post{{ i.id }}'>

      {% endif %}

      <div class="caption">
        <h2 style="font-size:45px;color:rgba(0,0,255,0.8);"><img src="/static/img/{{ i.tips_type }}.jpg" style="width:37px;height:37px;">&nbsp;&nbsp;<b>{{ i.title }}</b>    &nbsp;&nbsp;&nbsp;&nbsp;<small style="font-size:17px;">{{ i.timestamp|timesince }}</small></h2>

        <br/>
        <p>{{i.content|linebreaks|truncatechars:226}}</p>
        <a href="{% url 'posts:detail' id=i.id %}" <button class="btn btn-primary">View</button></a>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<div class="pagination">
<span class="step-links">
{% if name.has_previous %}
<a href="?page={{ name.previous_page_number }}">previous</a>
{% endif %}
<span class="current">
Page {{ name.number }} of {{ name.paginator.num_pages }}.
</span>
{% if name.has_next %}
<a href="?page={{ name.next_page_number }}">next</a>
{% endif %}
</span>
</div>

</div>
{% endblock %}